name: fortexx_cardsfunction_api - TST Build

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, TST]
    environment: TST

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Change to '10.0.x' if your project is updated to .NET 10

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: dotnet restore
        run: dotnet restore
        working-directory: Status_HyperpayFunction

      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
        working-directory: Status_HyperpayFunction

      - name: dotnet publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: Status_HyperpayFunction

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cardsfunction_api_tst
          path: Status_HyperpayFunction/publish
          retention-days: 30
