name: fortexx_cardsfunction_api - TST Build

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, TST]
    environment: TST

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'
        dotnet-install-dir: 'C:\dotnet'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: dotnet restore
      run: dotnet restore
      working-directory: Status_HyperpayFunction

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore
      working-directory: Status_HyperpayFunction

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cardsfunction_api_tst
        path: ${{ github.workspace }}\Status_HyperpayFunction\bin\Release
        retention-days: 30
